### ISSUE TITLE
FileNotFoundError: File b'/Users/benja/code/jester/data/labels.csv' does not exist

### ISSUE THREAD

**Issue by monajalal** [benjafire/CozmoGestureRegonize#2]
Hey Can you please share the labels.csv with me?

```
mona@Mona:~/code/gesture/CozmoGestureRegonize$ python train.py 
/home/mona/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 87, in <module>
    train("small_c3d")
  File "train.py", line 42, in train
    data = CNN3DDataLoader(data_dir, seq_length=seq_length, n_videos=n_videos, labels = labels_want)
  File "/home/mona/code/gesture/CozmoGestureRegonize/data.py", line 87, in __init__
    DataLoader.__init__(self, data_dir, n_videos, labels)
  File "/home/mona/code/gesture/CozmoGestureRegonize/data.py", line 27, in __init__
    self.get_labels(labels)
  File "/home/mona/code/gesture/CozmoGestureRegonize/data.py", line 37, in get_labels
    self.labels_df = pd.read_csv(path, names=['label'])
  File "/home/mona/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/Users/benja/code/jester/data/labels.csv' does not exist
```

**Comment by benja-wu** [comment]
Sure, as your wish, i  will  commit it soon. Actually, label.csv is provided in https://20bn.com/datasets/jester. You can download the dataset in that website included this file.
